import type { Step } from "./types";

export const BLOCKS = [
  { name: "Negócio", steps: [1, 2] },
  { name: "Mercado", steps: [3, 4, 5] },
  { name: "Modelo", steps: [6, 7] },
  { name: "Contexto", steps: [8, 9, 10, 11] },
  { name: "Marca", steps: [12, 13] },
];

export const STEPS: Step[] = [
  // BLOCO 1 — NEGÓCIO
  {
    id: 1,
    block: "Negócio",
    blockIndex: 0,
    title: "Área de Negócio",
    description: "Em que área actua o seu negócio? Escolha a que mais se aproxima.",
    type: "single-select",
    options: [
      { label: "Tecnologia / Software", icon: "Monitor" },
      { label: "Restauração / Alimentação", icon: "UtensilsCrossed" },
      { label: "Saúde / Clínicas", icon: "HeartPulse" },
      { label: "Educação / Formação", icon: "BookOpen" },
      { label: "Retalho / Comércio", icon: "ShoppingBag" },
      { label: "Imobiliário", icon: "Building" },
      { label: "Logística / Transporte", icon: "Truck" },
      { label: "Serviços Financeiros", icon: "Landmark" },
      { label: "Beleza / Estética", icon: "Sparkles" },
      { label: "Agricultura / Agro", icon: "Leaf" },
      { label: "Construção / Engenharia", icon: "HardHat" },
      { label: "Turismo / Hotelaria", icon: "Plane" },
      { label: "Entretenimento / Média", icon: "PlayCircle" },
      { label: "Consultoria", icon: "BarChart" },
      { label: "Outro", icon: "Pencil" },
    ],
  },
  {
    id: 2,
    block: "Negócio",
    blockIndex: 0,
    title: "Fase do Negócio",
    description: "Em que fase está o seu negócio? Seja honesto — não há resposta errada.",
    type: "single-select",
    options: [
      {
        label: "Não tenho nenhuma ideia",
        icon: "HelpCircle",
        conditionalFields: [
          { label: "Temas ou áreas que te interessam", placeholder: "Ex: tecnologia, saúde, educação..." },
          { label: "Competências ou experiência que tens", placeholder: "Ex: marketing, programação, vendas..." },
        ],
      },
      {
        label: "Só tenho a ideia",
        icon: "Lightbulb",
        conditionalFields: [
          { label: "Descreve a tua ideia em poucas palavras", placeholder: "Ex: app de entregas para zonas rurais..." },
          { label: "O que te motivou a pensar nesta ideia?", placeholder: "Ex: vi uma necessidade no meu bairro..." },
        ],
      },
      {
        label: "Já testei com alguns clientes",
        icon: "Users",
        conditionalFields: [
          { label: "Quantos clientes já tens?", placeholder: "Ex: 15 clientes activos" },
          { label: "Qual foi o principal feedback?", placeholder: "Ex: adoram a velocidade mas querem mais opções..." },
        ],
      },
      {
        label: "Já gero receita",
        icon: "DollarSign",
        conditionalFields: [
          { label: "Qual a receita mensal actual (aprox.)?", placeholder: "Ex: 500.000 Kz / mês" },
          { label: "Qual o maior desafio agora?", placeholder: "Ex: encontrar clientes novos..." },
        ],
      },
      {
        label: "Quero escalar o que já existe",
        icon: "TrendingUp",
        conditionalFields: [
          { label: "Qual o principal obstáculo ao crescimento?", placeholder: "Ex: falta de capital, equipa pequena..." },
          { label: "Que objectivo queres atingir em 12 meses?", placeholder: "Ex: duplicar a receita, abrir 2ª loja..." },
        ],
      },
    ],
  },

  // BLOCO 2 — MERCADO
  {
    id: 3,
    block: "Mercado",
    blockIndex: 1,
    title: "Problema que Resolve",
    description: "Qual o principal problema que resolve? Pense no cliente, não no produto.",
    type: "single-select",
    options: [
      { label: "Poupa tempo", icon: "Clock" },
      { label: "Poupa dinheiro", icon: "PiggyBank" },
      { label: "Substitui algo caro ou difícil de encontrar", icon: "Replace" },
      { label: "Dá acesso a algo que não existe no mercado", icon: "Key" },
      { label: "Melhora uma experiência má", icon: "ThumbsUp" },
      { label: "Conecta pessoas ou negócios", icon: "Link" },
      { label: "Aumenta segurança", icon: "Shield" },
      { label: "Aumenta produtividade", icon: "Zap" },
      { label: "Resolve um problema social ou ambiental", icon: "Globe" },
      { label: "Outro", icon: "Pencil" },
    ],
  },
  {
    id: 4,
    block: "Mercado",
    blockIndex: 1,
    title: "Cliente Principal",
    description: "Quem é o seu cliente principal? Pode escolher até 3.",
    type: "multi-select",
    maxSelect: 3,
    options: [
      { label: "Jovens 18–30", icon: "User" },
      { label: "Adultos 30–50", icon: "UserCheck" },
      { label: "Seniores 50+", icon: "UserCog" },
      { label: "Famílias", icon: "Home" },
      { label: "Estudantes", icon: "GraduationCap" },
      { label: "Freelancers", icon: "Laptop" },
      { label: "Empresas pequenas", icon: "Building2" },
      { label: "Grandes empresas", icon: "Factory" },
      { label: "Governo / Instituições", icon: "Landmark" },
      { label: "Profissionais de saúde", icon: "Stethoscope" },
      { label: "Mercado internacional", icon: "Globe2" },
      { label: "Outro", icon: "Pencil" },
    ],
  },
  {
    id: 5,
    block: "Mercado",
    blockIndex: 1,
    title: "Diferenciadores",
    description: "O que torna a sua oferta diferente? Escolha até 3.",
    type: "multi-select",
    maxSelect: 3,
    options: [
      { label: "Preço mais acessível", icon: "BadgeDollarSign" },
      { label: "Mais rápido que a concorrência", icon: "Rocket" },
      { label: "Mais simples de usar", icon: "Smile" },
      { label: "Focado no mercado local", icon: "MapPin" },
      { label: "Melhor suporte ao cliente", icon: "Headphones" },
      { label: "Tecnologia exclusiva", icon: "Cpu" },
      { label: "Personalização do serviço", icon: "Settings" },
      { label: "Qualidade superior", icon: "Award" },
      { label: "Sustentabilidade", icon: "Leaf" },
      { label: "Maior segurança", icon: "ShieldCheck" },
      { label: "Experiência mobile", icon: "Smartphone" },
      { label: "Inteligência artificial", icon: "Brain" },
      { label: "Entrega rápida / ao domicílio", icon: "Package" },
      { label: "Confiança / reputação local", icon: "Star" },
      { label: "Outro", icon: "Pencil" },
    ],
  },

  // BLOCO 3 — MODELO
  {
    id: 6,
    block: "Modelo",
    blockIndex: 2,
    title: "Modelo de Receita",
    description: "Como vai ganhar dinheiro? Escolha o modelo principal.",
    type: "single-select",
    options: [
      { label: "Subscrição mensal / anual", icon: "RefreshCw" },
      { label: "Venda única por produto", icon: "ShoppingCart" },
      { label: "Comissão por transacção", icon: "Percent" },
      { label: "Publicidade", icon: "Megaphone" },
      { label: "Freemium (gratuito + versão paga)", icon: "Gift" },
      { label: "Projectos / Consultoria", icon: "Briefcase" },
      { label: "Licenciamento", icon: "FileKey" },
      { label: "Marketplace / Intermediação", icon: "Store" },
      { label: "SaaS (Software as a Service)", icon: "Cloud" },
      { label: "Formação / Cursos", icon: "GraduationCap" },
      { label: "Aluguer / Arrendamento", icon: "Key" },
      { label: "Venda por grosso", icon: "Boxes" },
      { label: "Outro", icon: "Pencil" },
    ],
  },
  {
    id: 7,
    block: "Modelo",
    blockIndex: 2,
    title: "Números Base",
    description:
      "Estas informações ajudam a calcular as projecções financeiras do teu plano.",
    type: "numeric-fields",
    numericFields: [
      {
        key: "averagePrice",
        label: "Preço médio do produto ou serviço",
        placeholder: "Ex: 15.000",
      },
      {
        key: "investment",
        label: "Quanto podes investir para começar?",
        placeholder: "Ex: 500.000",
      },
    ],
    subSelect: {
      label: "Como vai chegar ao seu cliente?",
      maxSelect: 3,
      options: [
        { label: "WhatsApp / WhatsApp Business", icon: "MessageCircle" },
        { label: "Instagram / Facebook", icon: "Instagram" },
        { label: "Loja física", icon: "Store" },
        { label: "Site ou e-commerce", icon: "Globe" },
        { label: "Marketplace (Jumia, OLX, etc.)", icon: "ShoppingBag" },
        { label: "Boca a boca / referências", icon: "Users" },
        { label: "Vendedor presencial", icon: "UserCheck" },
        { label: "Email marketing", icon: "Mail" },
        { label: "Outro", icon: "Pencil" },
      ],
    },
  },

  // BLOCO 4 — CONTEXTO
  {
    id: 8,
    block: "Contexto",
    blockIndex: 3,
    title: "Localização",
    description: "Onde vai operar o seu negócio? Onde estão os seus clientes principais?",
    type: "single-select",
    options: [
      { label: "Apenas online — sem localização física", icon: "Wifi" },
      { label: "Local (cidade / bairro específico)", icon: "MapPin" },
      { label: "Regional — várias cidades ou províncias", icon: "Map" },
      { label: "Nacional — todo o país", icon: "Flag" },
      { label: "Internacional — múltiplos países", icon: "Globe" },
    ],
  },
  {
    id: 9,
    block: "Contexto",
    blockIndex: 3,
    title: "Equipa",
    description: "Como é a sua equipa? Quem está a trabalhar neste projecto?",
    type: "single-select",
    options: [
      { label: "Trabalho sozinho(a) — fundador único", icon: "User" },
      { label: "Co-fundadores (2–3 pessoas)", icon: "Users" },
      { label: "Pequena equipa (até 10 pessoas)", icon: "UsersRound" },
      { label: "Equipa média (10–50 pessoas)", icon: "Building2" },
      { label: "Estou a recrutar — ainda a construir", icon: "UserPlus" },
    ],
  },
  {
    id: 10,
    block: "Contexto",
    blockIndex: 3,
    title: "Prazo de Lançamento",
    description: "Em quanto tempo quer lançar? Isto define o cronograma do plano.",
    type: "single-select",
    options: [
      { label: "Em menos de 1 mês", icon: "Zap" },
      { label: "Entre 1 a 3 meses", icon: "Calendar" },
      { label: "Entre 3 a 6 meses", icon: "CalendarDays" },
      { label: "Entre 6 meses a 1 ano", icon: "CalendarRange" },
      { label: "Mais de 1 ano", icon: "CalendarClock" },
    ],
  },
  {
    id: 11,
    block: "Contexto",
    blockIndex: 3,
    title: "Objectivo Principal",
    description: "Qual o seu objectivo principal? O que pretende alcançar com este negócio?",
    type: "single-select",
    options: [
      { label: "Gerar rendimento estável e sustentável", icon: "TrendingUp" },
      { label: "Crescer rapidamente e escalar", icon: "Rocket" },
      { label: "Atrair investidores externos", icon: "HandCoins" },
      { label: "Vender o negócio em 3 a 5 anos", icon: "Handshake" },
      { label: "Impacto social ou ambiental", icon: "Heart" },
      { label: "Criar um produto ou marca global", icon: "Globe" },
    ],
  },

  // BLOCO 5 — MARCA
  {
    id: 12,
    block: "Marca",
    blockIndex: 4,
    title: "Nome do Negócio",
    description: "Escreva o nome ou peça sugestões à IA.",
    type: "text-input",
    hasAiGenerate: true,
    placeholder: "O nome do seu negócio...",
  },
  {
    id: 13,
    block: "Marca",
    blockIndex: 4,
    title: "Identidade Visual",
    description: "Como quer a identidade visual? Duas escolhas numa só ecrã.",
    type: "dual-select",
    dualGroups: [
      {
        title: "Estilo de Logo",
        description: "Pense na impressão que quer causar.",
        options: [
          { label: "Moderno e minimalista", icon: "Minus" },
          { label: "Corporativo e sério", icon: "Briefcase" },
          { label: "Criativo e colorido", icon: "Palette" },
          { label: "Tecnológico / Futurista", icon: "Cpu" },
          { label: "Tradicional e confiável", icon: "Shield" },
        ],
      },
      {
        title: "Tipo de Logo",
        description: "Escolher apenas um.",
        options: [
          { label: "Logótipo (Wordmark)", icon: "Type" },
          { label: "Monograma (Lettermark)", icon: "Hash" },
          { label: "Símbolo / Ícone (Brandmark)", icon: "Circle" },
          { label: "Logo Combinado", icon: "Layers" },
          { label: "Emblema", icon: "Shield" },
          { label: "Mascote", icon: "Smile" },
          { label: "Logo Abstracto", icon: "Hexagon" },
        ],
      },
    ],
  },
];
